# Generated by Django 6.0.6 on 2026-07-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('student_first_name', models.CharField(max_length=255)),
                ('student_last_name', models.CharField(max_length=255)),
                ('student_age', models.DateField()),
                ('details', models.CharField()),
            ],
        ),
    ]
