# Generated by Django 6.0.6 on 2026-09-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_enquiry_gender_alter_enquiry_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_lastname', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField()),
                ('language_spoken_at_home', models.CharField()),
                ('nationality', models.CharField()),
                ('state_of_origin', models.CharField(choices=[('AB', 'Abia'), ('AD', 'Adamawa'), ('AK', 'Akwa Ibom'), ('AN', 'Anambra'), ('BA', 'Bauchi'), ('BY', 'Bayelsa'), ('BE', 'Benue'), ('BO', 'Borno'), ('CR', 'Cross River'), ('DE', 'Delta'), ('EB', 'Ebonyi'), ('ED', 'Edo'), ('EK', 'Ekiti'), ('EN', 'Enugu'), ('FC', 'Federal Capital Territory'), ('GO', 'Gombe'), ('IM', 'Imo'), ('JI', 'Jigawa'), ('KD', 'Kaduna'), ('KN', 'Kano'), ('KT', 'Katsina'), ('KE', 'Kebbi'), ('KO', 'Kogi'), ('KW', 'Kwara'), ('LA', 'Lagos'), ('NA', 'Nasarawa'), ('NI', 'Niger'), ('OG', 'Ogun'), ('ON', 'Ondo'), ('OS', 'Osun'), ('OY', 'Oyo'), ('PL', 'Plateau'), ('RI', 'Rivers'), ('SO', 'Sokoto'), ('TA', 'Taraba'), ('YO', 'Yobe'), ('ZA', 'Zamfara')], max_length=2)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('family_size', models.IntegerField()),
                ('name_of_last_school', models.CharField()),
                ('last_school_startdate', models.DateField()),
                ('last_school_enddate', models.DateField()),
                ('position_in_last_school', models.CharField()),
                ('reason_for_leaving', models.CharField()),
                ('class_expexting_admission', models.CharField()),
                ('transport_service', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO')),
                ('any_certificate', models.CharField(max_length=255)),
                ('vision', models.CharField()),
                ('hearing', models.CharField()),
                ('speech', models.CharField()),
                ('general_vitality', models.CharField()),
                ('disability', models.CharField()),
                ('father_title', models.CharField()),
                ('father_name', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('office_address', models.CharField()),
                ('home_address', models.CharField()),
                ('father_phone', models.IntegerField()),
                ('father_email', models.EmailField(max_length=254)),
                ('mother_title', models.CharField()),
                ('mother_name', models.CharField(max_length=255)),
                ('mo_occupation', models.CharField(max_length=255)),
                ('mo_office_address', models.CharField()),
                ('mo_home_address', models.CharField()),
                ('mother_phone', models.IntegerField()),
                ('mother_email', models.EmailField(max_length=254)),
                ('gd_title', models.CharField()),
                ('gd_name', models.CharField(max_length=255)),
                ('gd_occupation', models.CharField(max_length=255)),
                ('gd_office_address', models.CharField()),
                ('gd_home_address', models.CharField()),
                ('gd_phone', models.IntegerField()),
                ('gd_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('parent_name', models.CharField(max_length=100)),
            ],
        ),
    ]
