# Generated by Django 6.0.6 on 2026-09-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_apply_sories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sories',
            new_name='Stories',
        ),
    ]
