# Generated by Django 6.0.6 on 2026-09-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_sories_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_img', models.ImageField(blank=True, null=True, upload_to='gallery/')),
            ],
        ),
        migrations.AlterField(
            model_name='stories',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='stories_img/'),
        ),
    ]
