# Generated by Django 6.0.6 on 2026-09-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gallery_alter_stories_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='father_title',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
