# Generated by Django 6.0.6 on 2026-09-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_apply_father_title_alter_stories_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='student_img',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='stories',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='stories_img/'),
        ),
    ]
